server:
  port: 8080

spring:
  application:
    name: osheeep-server

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
    packages-to-scan: com.osheeep.server
    paths-to-match: /api/**
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
